name: geo-env
channels:
    - conda-forge
dependencies:
    - cartopy
    - geopandas
    - keplergl
    - palettable
    - localtileserver
    - owslib
    - plotly
    - streamlit
    - streamlit-folium
    - streamlit-bokeh-events
    - tropycal
    - geemap
    - leafmap