name: geo
channels:
  - conda-forge
dependencies:
  - gdal
  - pip
  - pip:
      - geopandas
      - keplergl
      - streamlit
      - localtileserver
      - palettable
      - streamlit-folium
      - streamlit-keplergl
      - streamlit-bokeh-events
      - git+git://github.com/giswqs/leafmap
      - git+git://github.com/giswqs/geemap
